version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Building Corby
          command: gradle shadowJar

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Renaming Jar
          command: |
            target=$(ls build/libs | grep all.jar)
            echo ${$target//*/$CIRCLE_BUILD_NUM}
            mv build/libs/$target build/libs/$(echo ${$target//*/${CIRCLE_BUILD_NUM}})

      - store_artifacts:
          path: build/libs